name: 'Start ECS services'
description: 'Start ECS services in a given environment.'

inputs:
  service-names:
    required: true
    description: 'Space-separated list of ECS service names to stop.'
  environment:
    required: true
  desired_count:
    required: false
    default: '1'
  region:
    required: false
    default: 'eu-west-2'
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v5
    - id: config
      run: |
        case "${{ inputs.environment }}" in
          development)
            ACCOUNT_ID="844815912454"
            ;;
          staging)
            ACCOUNT_ID="451934005581"
            ;;
          production)
            ACCOUNT_ID="382373577178"
            ;;
          *)
            echo "Invalid environment: ${{ inputs.environment }}"
            exit 1
            ;;
        esac

        echo "role_to_assume=arn:aws:iam::${ACCOUNT_ID}:role/GithubActions-ECS-Deployments-Role" >> "$GITHUB_OUTPUT"
      shell: bash
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ steps.config.outputs.role_to_assume }}
        aws-region: ${{ inputs.region }}
    - run: |
        CLUSTER="trade-tariff-cluster-${{ inputs.environment }}"
        REGION="${{ inputs.region }}"
        DESIRED_COUNT="${{ inputs.desired_count }}"

        SUCCEEDED=()
        FAILED=()

        for SERVICE_NAME in ${{ inputs.service-names }}; do
          echo "::group::Starting service: $SERVICE_NAME"

          # Check if service exists first
          if ! aws ecs describe-services \
            --cluster "$CLUSTER" \
            --services "$SERVICE_NAME" \
            --region "$REGION" \
            --query "services[?status=='ACTIVE'].serviceName" \
            --output text | grep -q "$SERVICE_NAME"; then
            echo "::error::Service '$SERVICE_NAME' does not exist or is not active in cluster '$CLUSTER'"
            FAILED+=("$SERVICE_NAME (not found)")
            echo "::endgroup::"
            continue
          fi

          # Start the service
          if aws ecs update-service \
            --cluster "$CLUSTER" \
            --service "$SERVICE_NAME" \
            --desired-count "$DESIRED_COUNT" \
            --region "$REGION" \
            --output text \
            --query "service.{name:serviceName,desired:desiredCount,running:runningCount}" > /dev/null; then
            echo "::notice::✓ Started $SERVICE_NAME (desired count: $DESIRED_COUNT)"
            SUCCEEDED+=("$SERVICE_NAME")
          else
            echo "::error::✗ Failed to start $SERVICE_NAME"
            FAILED+=("$SERVICE_NAME")
          fi

          echo "::endgroup::"
        done

        # Print summary
        echo ""
        echo "=========================================="
        echo "Summary:"
        echo "=========================================="

        if [ ${#SUCCEEDED[@]} -gt 0 ]; then
          echo "::notice::✓ Successfully started ${#SUCCEEDED[@]} service(s):"
          for svc in "${SUCCEEDED[@]}"; do
            echo "::notice::  - $svc"
          done
        fi

        if [ ${#FAILED[@]} -gt 0 ]; then
          echo "::error::✗ Failed to start ${#FAILED[@]} service(s):"
          for svc in "${FAILED[@]}"; do
            echo "::error::  - $svc"
          done
          exit 1
        fi

        echo "::notice::All services started successfully!"
      shell: bash
