name: 'Build and push the Docker image'
description: 'Builds the Docker image and pushes it to the ECR repository.'

inputs:
  ecr-url:
    required: true
  ref:
    required: true
  region:
    required: false
    default: 'eu-west-2'
  role-to-assume:
    description: 'The IAM role ARN to assume for AWS operations.'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - id: role-to-assume
      run: |
        if [ -z "${{ inputs.role-to-assume }}" ]; then
          echo "::warning::Falling back to IAM_ROLE_ARN environment variable. Please update to use role-to-assume input."
          echo "role_to_assume=$IAM_ROLE_ARN" >> "$GITHUB_OUTPUT"
        else
          echo "::notice::Using explicit role-to-assume input: ${{ inputs.role-to-assume }}"
          echo "role_to_assume=${{ inputs.role-to-assume }}" >> "$GITHUB_OUTPUT"
        fi
      shell: bash
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ steps.role-to-assume.outputs.role_to_assume }}
        aws-region: ${{ inputs.region }}
    - id: resolved-ref
      run: |
        REF=${{ inputs.ref }}

        if ! git rev-parse --verify "$REF" 2>/dev/null; then
          echo "::error::The ref $REF does not exist in the Git repository."
          exit 1
        else
          echo "::notice::Resolved ref: $(git rev-parse --short "$REF")"
        fi

        echo RESOLVED_REF=$(git rev-parse --short "$REF") >> "$GITHUB_OUTPUT"
      shell: bash
    - run: |
        REPO_NAME=$(echo "${{ inputs.ecr-url }}" | cut -d'/' -f2)
        REF=${{ steps.resolved-ref.outputs.RESOLVED_REF }}
        EXISTING_IMAGE_NAME="${{ inputs.ecr-url }}:$REF"

        aws ecr get-login-password --region ${{ inputs.region }} \
          | docker login --username AWS --password-stdin "${{ inputs.ecr-url }}"

        if aws ecr describe-images \
          --repository-name "$REPO_NAME" \
          --image-ids imageTag="$REF" \
          --region "${{ inputs.region }}" \
          > /dev/null 2>&1; then
          echo "::notice::Image $EXISTING_IMAGE_NAME already exists in ECR. Creating a tag for this release."
        else
          echo "::error::Image $EXISTING_IMAGE_NAME not found in ECR. Fatal skipping tagging"
          exit 1
        fi

        RELEASE_IMAGE_NAME="${{ inputs.ecr-url }}:release-$(date +"%Y%m%d-%H%M")"

        docker pull $EXISTING_IMAGE_NAME
        docker tag $EXISTING_IMAGE_NAME $RELEASE_IMAGE_NAME
        docker push $RELEASE_IMAGE_NAME

        echo "::notice::Successfully built and pushed $RELEASE_IMAGE_NAME"
      shell: bash
