---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-merge-conflict

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.10.0
    hooks:
      - id: shellcheck
        args: ["--severity=error"]

  - repo: https://github.com/rhysd/actionlint.git
    rev: v1.7.7
    hooks:
      - id: actionlint-docker

  - repo: https://github.com/trufflesecurity/trufflehog
    rev: v3.88.20
    hooks:
      - id: trufflehog
