name: "Fetch AWS Secrets"
description: "Retrieve AWS Secrets Manager secrets and store them in a file of environment variables"

inputs:
  secret-name:
    description: "Name of the secret in AWS Secrets Manager"
    required: true
  env-file:
    description: 'Path to the environment file'
    required: false
    default: '.env'
  role-to-assume:
    description: 'The IAM role ARN to assume for AWS operations.'
    required: true
  region:
    required: false
    default: 'eu-west-2'

runs:
  using: "composite"
  steps:
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.role-to-assume }}
        aws-region: ${{ inputs.region }}

    - name: Fetch and store secrets
      shell: bash
      run: |
        aws secretsmanager get-secret-value \
          --secret-id "${{ inputs.secret-name }}" \
          --query "SecretString" \
          --output text \
          | jq -r 'to_entries[] | "\(.key)=\"\(.value)\""' > "${{ inputs.env-file }}"
