name: "Fetch AWS Secrets"
description: "Retrieve AWS Secrets Manager secrets and store them in a file of environment variables"

inputs:
  secret-name:
    description: "Name of the secret in AWS Secrets Manager"
    required: true
  env-file:
    description: 'Path to the environment file'
    required: false
    default: '.env'
  region:
    required: false
    default: 'eu-west-2'
  role-to-assume:
    description: 'The IAM role ARN to assume for AWS operations.'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - id: role-to-assume
      run: |
        if [ -z "${{ inputs.role-to-assume }}" ]; then
          echo "::warning::Falling back to IAM_ROLE_ARN environment variable. Please update to use role-to-assume input."
          echo "role_to_assume=$IAM_ROLE_ARN" >> "$GITHUB_OUTPUT"
        else
          echo "::notice::Using explicit role-to-assume input: ${{ inputs.role-to-assume }}"
          echo "role_to_assume=${{ inputs.role-to-assume }}" >> "$GITHUB_OUTPUT"
        fi
      shell: bash
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ steps.role-to-assume.outputs.role_to_assume }}
        aws-region: ${{ inputs.region }}

    - name: Fetch and store secrets
      shell: bash
      run: |
        aws secretsmanager get-secret-value \
          --secret-id "${{ inputs.secret-name }}" \
          --query "SecretString" \
          --output text \
          | jq -r 'to_entries[] | "\(.key)=\"\(.value)\""' > "${{ inputs.env-file }}"
