name: "Fetch AWS Secrets"
description: "Retrieve AWS Secrets Manager secrets and store them in a file of environment variables"

inputs:
  secret-name:
    description: "Name of the secret in AWS Secrets Manager"
    required: true
  env-file:
    description: 'Path to the environment file'
    required: false
    default: '.env'
  role-to-assume:
    description: 'The IAM role ARN to assume for AWS operations.'
    required: true
  region:
    required: false
    default: 'eu-west-2'

runs:
  using: "composite"
  steps:
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.role-to-assume }}
        aws-region: ${{ inputs.region }}

    - name: Fetch, store and mask secrets
      shell: bash
      run: |
        SECRET_JSON=$(aws secretsmanager get-secret-value \
          --secret-id "${{ inputs.secret-name }}" \
          --query "SecretString" \
          --output text)

          if [ -z "$SECRET_JSON" ]; then
            echo "Error: No secret data retrieved"
            exit 1
          fi

          TEMP_FILE=$(mktemp)
          echo "$SECRET_JSON" > "$TEMP_FILE"

          jq -r '
            to_entries[]
            | select(.value | type == "string")
            | select(.value | length > 8)
            | "::add-mask::" + .value
          ' "$TEMP_FILE"

           jq -r 'to_entries[] | "\(.key)=\"\(.value)\""' "$TEMP_FILE" > "${{ inputs.env-file }}"

           rm -f "$TEMP_FILE"
