name: 'Apply Terraform'
description: 'Run a terraform apply command to apply the changes.'

env:
  TF_INPUT: 0
  TF_IN_AUTOMATION: 1
  TERRAFORM_VERSION: 1.12

inputs:
  environment:
    required: true
    description: 'The environment to deploy to.'
  ref:
    required: true
    description: 'The git ref to deploy.'
  ssh-key:
    required: true
    description: 'The SSH key to use for fetching modules from github.'
  role-to-assume:
    description: 'The IAM role ARN to assume for AWS operations.'
    required: true
  region:
    required: false
    default: 'eu-west-2'
runs:
  using: 'composite'
  steps:
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.role-to-assume }}
        aws-region: ${{ inputs.region }}
    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}
    - uses: trade-tariff/trade-tariff-tools/.github/actions/setup-ssh@main
      with:
        ssh-key: ${{ inputs.ssh-key }}
    - run: cd terraform && terraform init -backend-config=backends/${{ inputs.environment }}.tfbackend
      shell: bash
    - run: cd terraform && terraform apply -var-file=config_${{ inputs.environment }}.tfvars -auto-approve -lock-timeout=10m
      shell: bash
      env:
        TF_VAR_docker_tag: ${{ inputs.ref }}
