name: 'Apply Terraform'
description: 'Run a terraform apply command to apply the changes.'

env:
  TF_INPUT: 0
  TF_IN_AUTOMATION: 1
  TERRAFORM_VERSION: 1.12

inputs:
  environment:
    required: true
    description: 'The environment to deploy to.'
  ref:
    required: true
    description: 'The git ref to deploy.'
  region:
    required: false
    default: 'eu-west-2'
  ssh-key:
    required: true
    description: 'The SSH key to use for fetching modules from github.'
  role-to-assume:
    description: 'The IAM role ARN to assume for AWS operations.'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - id: role-to-assume
      run: |
        if [ -z "${{ inputs.role-to-assume }}" ]; then
          echo "::warning::Falling back to IAM_ROLE_ARN environment variable. Please update to use role-to-assume input."
          echo "role_to_assume=$IAM_ROLE_ARN" >> "$GITHUB_OUTPUT"
        else
          echo "::notice::Using explicit role-to-assume input: ${{ inputs.role-to-assume }}"
          echo "role_to_assume=${{ inputs.role-to-assume }}" >> "$GITHUB_OUTPUT"
        fi
      shell: bash
    - id: resolved-ref
      run: |
        REF=${{ inputs.ref }}

        if ! git rev-parse --verify "$REF" 2>/dev/null; then
          echo "::error::The ref $REF does not exist in the Git repository."
          exit 1
        else
          echo "::notice::Resolved ref: $(git rev-parse --short "$REF")"
        fi

        echo RESOLVED_REF=$(git rev-parse --short "$REF") >> "$GITHUB_OUTPUT"
      shell: bash
    - uses: actions/checkout@v4.1.0
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ steps.role-to-assume.outputs.role_to_assume }}
        aws-region: ${{ inputs.region }}
    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}
    - uses: trade-tariff/trade-tariff-tools/.github/actions/setup-ssh@main
      with:
        ssh-key: ${{ inputs.ssh-key }}
    - run: cd terraform && terraform init -backend-config=backends/${{ inputs.environment }}.tfbackend
      shell: bash
    - run: cd terraform && terraform apply -var-file=config_${{ inputs.environment }}.tfvars -auto-approve -lock-timeout=10m
      shell: bash
      env:
        TF_VAR_docker_tag: ${{ steps.resolved-ref.outputs.RESOLVED_REF }}
