name: 'Setup TFLint'
description: 'Setup TFLint for linting Terraform code'

inputs:
  github-token:
    description: 'GitHub token for API authentication'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Install TFLint
      uses: terraform-linters/setup-tflint@90f302c255ef959cbfb4bd10581afecdb7ece3e6 # v4.1.1
      with:
        tflint_version: latest
        tflint_wrapper: false
        github_token: ${{ inputs.github-token || github.token }}
