name: 'Setup TFLint'
description: 'Setup TFLint for linting Terraform code'

inputs:
  github-token:
    description: 'GitHub token for API authentication'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Install TFLint
      run: |
        if [ -n "${{ inputs.github-token }}" ]; then
          curl -s -H "Authorization: token ${{ inputs.github-token }}" \
            https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
        else
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
        fi
      shell: bash
