name: 'Setup TFLint'
description: 'Setup TFLint for linting Terraform code'

inputs:
  github-token:
    description: 'GitHub token for API authentication'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Install TFLint
      uses: terraform-linters/setup-tflint@6e87008f9dd1fe3e34e66aca6c97b4a69f72a7f4 # v4
      with:
        tflint_version: latest
        tflint_wrapper: false
        github_token: ${{ inputs.github-token || github.token }}
