name: 'Plan Terraform'
description: 'Run a terraform plan command to validate the changes.'

env:
  TF_INPUT: 0
  TF_IN_AUTOMATION: 1

inputs:
  environment:
    required: true
    description: 'The environment to verify with the plan.'
  ref:
    required: true
    description: 'The git ref we plan to deploy.'
  ssh-key:
    required: true
    description: 'The SSH key to use for fetching modules from github.'
  region:
    required: false
    default: 'eu-west-2'
runs:
  using: 'composite'
  steps:
    - id: resolved-ref
      run: |
        REF=${{ inputs.ref }}

        if ! git rev-parse --verify "$REF" 2>/dev/null; then
          echo "::error::The ref $REF does not exist in the Git repository."
          exit 1
        else
          echo "::notice::Resolved ref: $(git rev-parse --short "$REF")"
        fi

        echo RESOLVED_REF=$(git rev-parse --short "$REF") >> "$GITHUB_OUTPUT"
      shell: bash
    - uses: actions/checkout@v4.1.0
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ env.IAM_ROLE_ARN }}
        aws-region: ${{ inputs.region }}
    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.11.0
    - uses: trade-tariff/trade-tariff-tools/.github/actions/setup-ssh@main
      with:
        ssh-key: ${{ inputs.ssh-key }}
    - run: cd terraform && terraform init -backend-config=backends/${{ inputs.environment }}.tfbackend
      shell: bash
    - run: cd terraform && terraform plan -var-file=config_${{ inputs.environment }}.tfvars
      shell: bash
      env:
        TF_VAR_docker_tag: ${{ steps.resolved-ref.outputs.RESOLVED_REF }}
