name: axxy-tests

on:
  workflow_call:
    inputs:
      base-url:
        description: 'The base URL for the axxy tests'
        type: string
        required: true
      admin-url:
        description: 'The admin URL for the axxy tests'
        type: string
        required: true
      email:
        description: 'Email address for the axxy tests gh pages commit'
        type: string
        required: false
        default: 'trade-tariff-infrastructure-continuity<hmrc-trade-tariff-support-g@digital.hmrc.gov.uk>'

    secrets:
      slack-webhook:
        description: 'Slack webhook URL for notifications'
        required: true
      ssh-key:
        description: 'SSH private key used for commits'
        required: true
      basic-password:
        description: 'The basic auth password'
        required: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          cache: 'yarn'

      - run: yarn install

      - run: yarn playwright install --with-deps chromium

      - run: yarn run playwright test --workers 1
        env:
          ADMIN_URL: ${{ inputs.admin-url }}
          BASE_URL: ${{ inputs.base-url }}
          BASIC_PASSWORD: ${{ secrets.basic-password }}

      - run: cp node_modules/govuk-frontend/dist/govuk/assets/images/favicon.ico dist/favicon.ico

      - uses: trade-tariff/trade-tariff-tools/.github/actions/setup-ssh@main
        with:
          ssh-key: ${{ secrets.ssh-key }}

      - run: |
          yarn run gh-pages \
            --dist dist \
            --user "${{ inputs.email }}" \
            --silent \
            --nojekyll \
            --no-history

      - uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: "non-production-alerts"
          SLACK_USERNAME: "Accessibility Report"
          SLACK_WEBHOOK: ${{ secrets.slack-webhook }}
          SLACK_ICON_EMOJI: ":playwright:"
          SLACK_COLOR: success
          SLACK_TITLE: New Accessibility report generated
          SLACK_MESSAGE: https://trade-tariff.github.io/trade-tariff-frontend/accessibility-report.html
