name: 'Run database migrations'
description: 'Applies schema changes pre-deployment.'

inputs:
  environment:
    description: 'The name of the environment to perform the migration in'
    required: true
  region:
    required: false
    default: 'eu-west-2'
  role-to-assume:
    description: 'The IAM role ARN to assume for AWS operations.'
    required: true
  migration-task:
    description: 'The name of the task to use'
    required: true
  migration-overrides:
    description: 'Container overrides for running the task in JSON format.'
    required: true
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v6

    - uses: aws-actions/configure-aws-credentials@v6
      with:
        role-to-assume: ${{ inputs.role-to-assume }}
        aws-region: ${{ inputs.region }}

    - name: Apply database migration
      shell: bash
      run: |
        echo "::notice::Running migration task for ${{ inputs.environment }}..."
        overrides=$(jq -r -c '.' <<<'${{ toJSON(inputs.migration-overrides) }}')

        ${{ github.action_path }}/../../../bin/run-task -e ${{ inputs.environment }} -t ${{ inputs.migration-task }} -o "${overrides}"
